parameters: {  }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Entity/'

when@test:
    services:
        test.client.parameters:
            http_client_options:
                base_uri: 'http://localhost'
