api_platform:
  title: "MuscleMind API"
  version: "1.0.0"
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
    html: ["text/html"]
  exception_to_status:
    Symfony\Component\Serializer\Exception\ExceptionInterface: 400
    ApiPlatform\Exception\InvalidArgumentException: 400
